# THIS FILE GENERATED BY speXtra setup.py 
version = '0.25'
date    = '2022-07-12 17:00:00 GMT'
yaml_descriptions = """
- version : 0.4.2
  date : 2022-07-12
  comment : Updated DLC server to point to scopesim.univie.ac.at
"""